feat: реализованы требования тз
evgeniy-schekoldin/java-shareit pull request #2
Opened 2022-08-12 21:28 UTC by evgeniy-schekoldin

2022-08-13 22:27 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +
две пустые строки не нужны

2022-08-13 22:33 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +    public static Item updateItemFromDto(Item item, ItemDto itemDto) {
не очень понял, зачем для маппинга тут понадобилась отдельная библиотека
и что она тут делает?

если ты хочешь тут игнорить пустой id при апдейте item с помщью dto, то возникает вопрос, как вообще найдется нужный item, если в dto нет id, по которому искать в storage?

2022-08-13 22:33 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> -public class Booking {
скорее всего это понадобится в следующих спринтах

2022-08-13 22:34 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +public enum Status { WAITING, APPROVED, REJECTED, CANCELLED }
в джаве принято код класса писать с новой строки

2022-08-13 22:36 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +package ru.practicum.shareit.item.controller;
судя по ТЗ вас хотят познакомить с другой концепцией расположения классов по пакетам - Feature Layout
это когда классы разделяются не по тому, что они делают, а по фиче, к которой они относятся

поэтому все контроллеры, сервисы, модель и тд относящиеся к Item, находятся в пакете item

в общем, этот момент стоит еще раз явно проговорить с наставником
отпишись плз потом, что он скажет

2022-08-13 22:38 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.addItem(userId, itemDto);
лучше сделать, чтобы сервис отдавал сервисные объекты Item, а в контроллере уже мапить в ItemDto

этот сервис может понадобиться в другом сервисе и там dto объект будет выглядеть странно

2022-08-13 22:38 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto addItem(@RequestHeader(value = "X-Sharer-User-Id") long  userId,
хедер стоит вынести в константу

2022-08-13 22:39 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    boolean isUserItem(long itemId, long userId);
лучше назвать isOwner(itemId, userId)
а то по двум существительным не понятно, какое отношение двух объектов проверяется

2022-08-13 22:40 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    long itemId;
не должно быть глобавльного состояния в классе

2022-08-13 22:40 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    Map<Long, List<Item>> items = new HashMap<>();
private final

2022-08-13 22:42 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotEmpty(message = "Поле name объекта Item содержит недопустимое значение")
эту валидацию стоит сделать на dto, на сервисном объекте она не нужна

2022-08-13 22:44 UTC, makholin commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +    static ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
private final

2022-08-13 22:46 UTC, makholin requested changes
Нужно исправить замечания
Чаще всего замечания актуальны  для классов, связанных и с Item и с User, потому что код и логика у них похожи

2022-08-15 06:01 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +
исправил

2022-08-15 06:02 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> -public class Booking {
класс не удален, перенесен в ru.practicum.shareit.booking.model

2022-08-15 06:03 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +public enum Status { WAITING, APPROVED, REJECTED, CANCELLED }
исправил

2022-08-15 06:13 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto addItem(@RequestHeader(value = "X-Sharer-User-Id") long  userId,
исправил

2022-08-15 06:14 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    boolean isUserItem(long itemId, long userId);
исправил

2022-08-15 06:14 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    long itemId;
оставил так до следующего спринта

2022-08-15 06:15 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +    static ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
исправил

2022-08-15 06:16 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    Map<Long, List<Item>> items = new HashMap<>();
исправил

2022-08-15 06:17 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.addItem(userId, itemDto);
но ведь вроде так и есть: ru/practicum/shareit/**item**/controller/

2022-08-15 06:19 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +package ru.practicum.shareit.item.controller;
но ведь вроде так и есть: ru/practicum/shareit/**item**/controller/

2022-08-15 06:58 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.addItem(userId, itemDto);
исправлено

2022-08-17 06:45 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +    public static Item updateItemFromDto(Item item, ItemDto itemDto) {
нет больше библиотеки

2022-08-17 06:46 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotEmpty(message = "Поле name объекта Item содержит недопустимое значение")
валидация перенесена на дто

2022-08-18 12:40 UTC, makholin approved these changes
Работа принята

2022-08-19 11:06 UTC, merged