feat: реализованы требования тз
evgeniy-schekoldin/java-shareit pull request #3
Opened 2022-08-31 12:26 UTC by evgeniy-schekoldin

Добавлена работа с БД, функционал бронирования и комментарии.
По указанию наставника, переделал сервисы, чтобы они возвращали в контроллеры Dto-объекты.

2022-09-01 11:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @PostMapping("/bookings")
общую часть урла можно было оставить у класса 
`@RequestMapping(path = "/bookings")`

2022-09-01 11:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDtoOut addBooking(@Validated({Create.class}) @RequestBody BookingDtoIn bookingDtoIn,
классы лучше назвать `InboundBookingDto` и `OutboundBookingDto`,
или `BookingRequestDto` и `BookingResponseDto`

2022-09-01 11:56 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        try {
получение стейта из строки лучше вынести в приватный метод

2022-09-01 11:57 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                @RequestParam(defaultValue = "ALL") String state) {
"ALL" стоит вынести в константу

2022-09-01 12:14 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        try {
сделано

2022-09-01 12:14 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                @RequestParam(defaultValue = "ALL") String state) {
сделал

2022-09-01 12:23 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                () -> new EntityNotFoundException("addBooking: User not found")
стоит добавить в сообщения исключений невалидные данные (userId, itemId, date и тд), чтобы легче понять по логам в чем была проблема

2022-09-01 12:26 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        switch (state) {
`bookingRepository.getUserBookings(userId)` можно вызвать перед switch один раз
в switch он тоже вызывается один раз по факту, но код будет выглядеть проще

2022-09-01 12:27 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDtoOutShort addItem(@Validated(Create.class) @RequestBody ItemDtoIn itemDtoIn,
класс лучше назвать `ShortItemResponse` или `ShortItemResponseDto`

2022-09-01 12:27 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDtoOutShort addItem(@Validated(Create.class) @RequestBody ItemDtoIn itemDtoIn,
класс ItemDtoIn тоже стоит назвать по примерам, которые я выше писал

2022-09-01 12:28 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoOut.java
> +    private Boolean available;
можно использовать примитив

2022-09-01 12:30 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
код с аннотациями проще читать, если они упорядочены в порядке возрастания длины

2022-09-01 12:31 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "item_id")
обычно в таблице для сущности колонку с ее id  называют просто id
но и так можно оставить

2022-09-01 12:32 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoOut.java
> +    public static class ItemBookingDto {
нужно вынести в отдельные файлы

2022-09-01 12:32 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/CommentMapper.java
> +
достаточно одной пустой строки

2022-09-01 12:33 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/CommentMapper.java
> +    public static ItemDtoOut.ItemCommentDto toItemCommentDtoOut(Comment comment) {
класс Comment нужно вынести в отдельные файлы, это самостоятельная сущность

2022-09-01 12:35 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemRepository itemRepository,
можно заменить аннотацией RequiredArgConstructor

2022-09-01 12:37 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item item = itemRepository.findByIdAndOwnerId(itemId, userId).orElseThrow(
странно, что при поиске вещи по id и ownerId, она может быть forbidden (судя по логу)
тут либо название метода репозитория не раскрывает всей логики либо проблема в логе

2022-09-01 12:39 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        List<ItemDtoOut> itemsDtoOut = new ArrayList<>();
смесь работы из dto объектов и domain объектов выглядит очень запутанно
попробуй использовать в сервисах только классы-модель только domain слоя, а конвертацию в дто делать уже в контроллере

2022-09-01 12:41 UTC, makholin requested changes
Нужно исправить замечания

2022-09-01 13:01 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemRepository itemRepository,
исправил

2022-09-01 13:03 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item item = itemRepository.findByIdAndOwnerId(itemId, userId).orElseThrow(
по сути да, здесь просто NotFound

2022-09-01 13:03 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/CommentMapper.java
> +
убрал

2022-09-01 13:06 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "item_id")
исправил

2022-09-01 13:09 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
отсортировал во всех классах

2022-09-01 13:11 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoOut.java
> +    private Boolean available;
исправил

2022-09-01 13:25 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                () -> new EntityNotFoundException("addBooking: User not found")
добавил

2022-09-01 13:28 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoOut.java
> +    public static class ItemBookingDto {
сделал

2022-09-01 13:29 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/CommentMapper.java
> +    public static ItemDtoOut.ItemCommentDto toItemCommentDtoOut(Comment comment) {
сделал

2022-09-01 13:30 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        List<ItemDtoOut> itemsDtoOut = new ArrayList<>();
договорились оставить так

2022-09-02 08:29 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java
> +    long id;
поля должны быть private

2022-09-02 08:29 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemCommentDto.java
> +    LocalDateTime created;
тут тоже private

2022-09-02 08:30 UTC, makholin requested changes
Нужно добавить private для полей

2022-09-02 08:31 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java
> +    long id;
+

2022-09-02 08:31 UTC, evgeniy-schekoldin commented on src/main/java/ru/practicum/shareit/item/dto/ItemCommentDto.java
> +    LocalDateTime created;
+

2022-09-02 08:57 UTC, makholin approved these changes
работа принята

2022-09-02 08:59 UTC, merged